# Generated by Django 3.2 on 2024-01-03 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_post_like'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topic',
            options={'ordering': ['name']},
        ),
    ]
