# Generated by Django 3.2 on 2024-01-08 17:17

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_postreply_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postreply',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
