# Generated by Django 3.2 on 2024-01-10 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_alter_postreply_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postreply',
            options={'verbose_name_plural': 'Post Replies'},
        ),
    ]
