# Generated by Django 3.2 on 2024-02-08 15:20

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0009_alter_postreply_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PostReply',
            new_name='Comment',
        ),
    ]
