# Generated by Django 3.2 on 2024-02-15 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_rename_postreply_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-date_posted']},
        ),
    ]
