# Generated by Django 4.2 on 2024-03-05 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_alter_comment_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='user_created',
            field=models.BooleanField(default=False),
        ),
    ]
