# Generated by Django 4.2 on 2024-03-05 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_topic_user_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, default='post_images/default.webp', null=True, upload_to='post_images'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='image',
            field=models.ImageField(blank=True, default='topic_images/default.webp', null=True, upload_to='topic_images'),
        ),
    ]
