# Generated by Django 4.2 on 2024-04-19 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0026_rename_like_post_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='post',
            name='num_of_replies',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='total_post',
        ),
    ]
